packagereflectInspector.test

import java.io.Serializable;

public class PersonGenGen implements Serializable{

private String firstname;
private String lastname;
private String birthdate;
private Long personId;
private int i;


 //constructor autogenerated
public PersonGen(){}
public PersonGen(int a){}


public String printHello(){
return null;
}

private String getBirthdate(){
return birthdate;
}

private void setBirthdate(String birthdate){
this.birthdate=birthdate;
}

private String getFirstname(){
return firstname;
}

//missed get method in the input Class for field i
//get method autogenerated
private int geti(){
return i;
}

//missed get method in the input Class for field personId
//get method autogenerated
private Long getpersonId(){
return personId;
}

//missed get method in the input Class for field lastname
//get method autogenerated
private String getlastname(){
return lastname;
}

//missed set method in the input Class for field firstname
//set method autogenerated
private void setfirstname(String firstname){
this.firstname=firstname;
}

//missed set method in the input Class for field i
//set method autogenerated
private void seti(int i){
this.i=i;
}

//missed set method in the input Class for field personId
//set method autogenerated
private void setpersonId(Long personId){
this.personId=personId;
}

//missed set method in the input Class for field lastname
//set method autogenerated
private void setlastname(String lastname){
this.lastname=lastname;
}

}
